version: '3.8'

services:
  postgres-demo:
      container_name: postgres-demo
      image: postgres:15.2      
      volumes:
        - postgres_demo_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: demo
        POSTGRES_USER: demo_user
        POSTGRES_PASSWORD: demo_user
      ports:
        - 5434:5432
#      healthcheck:
#        test: ["CMD-SHELL", "pg_isready -d keycloak -U keycloak"]
#        interval: 10s
#        timeout: 3s
#        retries: 3
#
#  keycloak:
#    image: quay.io/keycloak/keycloak:22.0.1
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      #      KEYCLOAK_ADMIN: admin
#      #      KEYCLOAK_ADMIN_PASSWORD: admin
#      #      KC_DB_URL: jdbc:postgresql://postgres-ecard:5432/ecardkc
#      #      KC_DB_USERNAME: ecard
#      #      KC_DB_PASSWORD: ecard@123
#      #      KC_DB: postgres
#      #      KC_HOSTNAME: localhost
#
#    command:
#      - start-dev
#      #      - --import-realm
#      #    volumes:
#      #      - /home/keycloak/realm.json:/opt/keycloak/data/import/realm.json
#
#      # Uncomment the line b  elow if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
#    #      JDBC_PARAMS: "ssl=true"
#    #    entrypoint: /opt/keycloak/bin/kc.sh start
#    ports:
#      - '8081:8080'
#  #    depends_on:
#  #      - postgres-ecard


#  demo:
##    image: ecard-poc
#    image: demo:latest
#    container_name: demo
#    environment:
#      POSTGRES_DATABASE_HOST: postgres-demo
##    env_file:
##      - src/main/resources/local.env
#    ports:
#      - 8000:8080
#    depends_on:
#      - postgres-demo

# Persisted data across application restarts
volumes:
  postgres_demo_data: {}
#  cache:
#    driver: local


